### ISSUE TITLE
Хүсэлт - /update notebooks/

### ISSUE THREAD

**Issue by delgerdalai** [dl-ub-summer-school/2019#1]
Thank you guys

Симнар дээр хийсэн зүйлсээрээ github дээрх notebook -ээ update хийгээд явбал сайн байна. холоос сайн харагдахгүй байсан. 

Баярлалаа.

**Comment by gereltuya** [comment]
Семинарын материалууд шинэчлэгдсэн, та шалгаад үзээрэй, баярлалаа.
